version: '3'
services:
  parking-postgres:
    image: 'postgres:16.3-alpine'
    environment:
      POSTGRES_DB: parking_db
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --auth-host=trust
      # secrets
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      # secrets
    ports:
      - '5432:5432'
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    profiles:
      - kafka
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    profiles:
      - kafka
  eureka-server:
    image: 'eureka-server:0.0.1-SNAPSHOT'
    ports:
      - "8761:8761"
  cloud-gateway:
    image: 'cloud-gateway:0.0.1-SNAPSHOT'
    environment:
      ENV_EUREKA_HOST: eureka-server
    ports:
      - "80:8080"

  user-service:
    image: 'user-service:0.0.1-SNAPSHOT'
    environment:
      SPRING_PROFILES_ACTIVE: ${APP_PROFILE}
      ENV_POSTGRES_HOST: parking-postgres
      ENV_EUREKA_HOST: eureka-server
      ENV_JWT_EXPIRATION: 86400
      ENV_AWS_REGION: eu-central-1
      ENV_AWS_BUCKET: icu-cyclone-cars-public
      ENV_KAFKA_BOOTSTRAP_HOST: kafka
      # secrets
      ENV_POSTGRES_USERNAME: ${ENV_POSTGRES_USERNAME}
      ENV_POSTGRES_PASSWORD: ${ENV_POSTGRES_PASSWORD}
      ENV_JWT_SECRET: ${ENV_JWT_SECRET}
      ENV_AWS_ACCESS: ${ENV_AWS_ACCESS}
      ENV_AWS_SECRET: ${ENV_AWS_SECRET}
      # secrets
    ports:
      - "8110:8080"
    depends_on:
      - parking-postgres
  booking-service:
    image: 'booking-service:0.0.1-SNAPSHOT'
    environment:
      SPRING_PROFILES_ACTIVE: kyiv1,${APP_PROFILE}
      ENV_POSTGRES_HOST: parking-postgres
      ENV_EUREKA_HOST: eureka-server
      ENV_KAFKA_BOOTSTRAP_HOST: kafka
      # secrets
      ENV_POSTGRES_USERNAME: ${ENV_POSTGRES_USERNAME}
      ENV_POSTGRES_PASSWORD: ${ENV_POSTGRES_PASSWORD}
      ENV_JWT_SECRET: ${ENV_JWT_SECRET}
      # secrets
    ports:
      - "8120:8080"
    depends_on:
      - parking-postgres
